### ISSUE TITLE
There are no devices connected. Review your USB connection and try again.

### ISSUE THREAD

**Issue by MiguelCatalan** [pedrovgs/AndroidWiFiADB#18] opened 2015-10-26 07:40 UTC
I'm getting this error over and over.

``` shell
08:35:15 Android WiFi ADB: There are no devices connected. Review your USB connection and try again. 
08:35:27 Adb connection Error:Se ha forzado la interrupción de una conexión existente por el host remoto
08:35:28 Connection attempts: 1
```

Using Windows 10, AS 1.4 and One plus One device.

**Comment by johnwatsondev** [comment] 2015-10-26 10:37
Same issue. Mac OS X 10.11.1 , Nexus 5 , AS 1.4 stable channel and AndroidWiFiADB 1.2 .
`Android WiFi ADB: There are no devices connected. Review your USB connection and try again.`

**Comment by pedrovgs** [comment] 2015-10-26 20:34
@MiguelCatalan @johnwatsondev  can you try to execute this commands and paste the output here?

```
adb tcpip 5555
adb connect 192.168.2.131
Replace 192.168.2.131 with the IP assigned to your device.
```

Thanks!

**Comment by johnwatsondev** [comment] 2015-10-27 01:26
@pedrovgs 
![qq20151027-0 2x](https://cloud.githubusercontent.com/assets/12760754/10747109/9439c64e-7c8c-11e5-8b82-7ef69a4fa977.png)

**Comment by MiguelCatalan** [comment] 2015-10-27 08:08
@pedrovgs after running the first command

```
PS C:\Users\something> adb tcpip 5555
adb server is out of date.  killing...
* daemon started successfully *
```

And the plugin worked like charm

**Comment by pedrovgs** [comment] 2015-10-27 10:45
@johnwatsondev review your ADB installation.  There is something wrong there. I can't change the code of my plugin to get you adb installation working, sorry. I'm closing this issue. Maybe the problem is related to your device. Did you connect your USB cable to the device before to press the button? ;)

**Comment by pedrovgs** [comment] 2015-10-27 10:46
@MiguelCatalan AFAIK you know java and could be awesome if you reproduce the bug again and send me a PR with the fix. It's quite simple. What do you think?

**Closed as completed by pedrovgs** 2015-10-27 10:46 UTC
Labels: bug

**Comment by johnwatsondev** [comment] 2015-10-28 01:20
@pedrovgs Sorry about that i didn't read the **`Usage`** carefully. I didn't connect my device through cable with AS...  My fault. :sob:

**Comment by pedrovgs** [comment] 2015-10-28 07:42
No problem @johnwatsondev
