### ISSUE TITLE
Command not found. Review your Android SDK installation. Linux and Windows environments.

### ISSUE THREAD

**Issue by weiyideai520** [pedrovgs/AndroidWiFiADB#1] opened 2015-10-19 02:22 UTC
I'm sure you have installed android sdk，but still error.
what can i do?

**Comment by pedrovgs** [comment] 2015-10-19 08:00
Hi @weiyideai520 you have to configure your ANDROID_HOME environment var pointing at your Android SDK installation. Is this the answer to your question?

**Comment by lulumeya** [comment] 2015-10-19 08:27
I had same issue, and I configured ANDROID_HOME properly.
I want to know, how this plugin executes the command? It is not working on the variety context I think.

**Comment by pedrovgs** [comment] 2015-10-19 08:29
Here you have the class to execute commands https://github.com/pedrovgs/AndroidWiFiADB/blob/0a6af962f801e233a27092e26c22fdbe713325e9/src/main/java/com/github/pedrovgs/androidwifiadb/adb/CommandLine.java :)

**Comment by tomer1** [comment] 2015-10-19 08:29
same problem here ANDROID_HOME is configure correct. and I get the message "command not found"

**Comment by pedrovgs** [comment] 2015-10-19 08:30
@tomer1 are you using Windows?

**Comment by tomer1** [comment] 2015-10-19 08:30
linux

**Comment by pedrovgs** [comment] 2015-10-19 08:31
Can you paste here the output obtained executing `echo $ANDROID_HOME` in your terminal from your home directory?

**Comment by tomer1** [comment] 2015-10-19 08:32
~$ echo $ANDROID_HOME 
/home/tomer/Android/sdk/

**Comment by pedrovgs** [comment] 2015-10-19 08:32
@lulumeya are you also using Linux?

**Comment by lulumeya** [comment] 2015-10-19 08:34
@pedrovgs I am using os x
Can I know exactly what command is executed? like "adb version" ?

**Comment by pedrovgs** [comment] 2015-10-19 08:36
`adb version` is executed to know if `adb` is installed or not. 
`adb devices -l` is executed to get the list of connected devices.

@lulumeya @tomer1 can you execute these commands in your terminal and paste here the output?¿

**Comment by lulumeya** [comment] 2015-10-19 08:40
@pedrovgs here are the outputs
➜  ~  adb version
Android Debug Bridge version 1.0.32
Revision eac51f2bb6a8-android
➜  ~  adb devices -l
List of devices attached
ZX1G22CL8F             device usb:14200000 product:shamu model:Nexus_6 device:shamu

ANDROID_HOME is env variable, not a path variable, the studio is GUI application that does not contain the variables configured to shell. When you executes commands, may be need full path. Can you try it?

**Comment by pedrovgs** [comment] 2015-10-19 08:43
@lulumeya this is the code which gets the full adb path. When you build the plugin to generate a new release that build can't use path env vars.

``` java
private String getAdbPath() {
    String androidSdkPath = EnvironmentUtil.getValue("ANDROID_HOME");
    if (androidSdkPath == null) {
      return "";
    }
    return androidSdkPath + ADB_RELATIVE_PATH;
  }
```

**Comment by lulumeya** [comment] 2015-10-19 09:05
@pedrovgs I can't add env vars to which are executing the studio. my terminal has env vars, but studio it self doesn't.

**Comment by lulumeya** [comment] 2015-10-19 09:07
@pedrovgs 
![image](https://cloud.githubusercontent.com/assets/364983/10573682/30f832a6-768c-11e5-99f8-b0ab3dd06b9e.png)
but pref is set properly.

**Comment by lulumeya** [comment] 2015-10-19 09:10
FYI, I used file which you uploaded, I didn't build new.

**Comment by pedrovgs** [comment] 2015-10-19 09:10
The plugin needs the path to your android sdk intallation. Can't you configure your env vars just doing something like this? Or in your bash profile?

```
export ANDROID_HOME=<YOUR_SDK_PATH>
export PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools
source ~/.bash_profile
```

**Comment by lulumeya** [comment] 2015-10-19 09:11
@pedrovgs 
in my bash, It is configured correctly, but studio does not recognize it. :(

**Comment by pedrovgs** [comment] 2015-10-19 09:14
could that be a problem related to your Android Studio installation? A friend of mine had the same problem but declaring the env var got the plugin working perfectly :(

**Comment by santoshgistto** [comment] 2015-10-19 13:09
@pedrovgs  i am using ubuntu ,same issue

export ANDROID_HOME=/home/my_machine/android-sdks
export PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools

**Comment by pedrovgs** [comment] 2015-10-19 13:28
@santoshgistto I guess you are executing that command line sentences in your bash profile file, don't you?

**Comment by itxuye** [comment] 2015-10-19 14:21
Hi,I had same issue, and I configured ANDROID_HOME properly.I'm using the windows.Can i use it in windows ?Like this?
![1](https://cloud.githubusercontent.com/assets/9589686/10580341/a8ddcd94-76af-11e5-892c-9baabff682f1.png)
![2](https://cloud.githubusercontent.com/assets/9589686/10580348/b4245650-76af-11e5-8c71-a0bbc833557c.png)

**Comment by pedrovgs** [comment] 2015-10-19 14:29
I'll review if the plugin is working as should in windows or not. Sorry for the inconveniences.

**Comment by maoruibin** [comment] 2015-10-19 16:56
I read above conversations and I meet same problem also , and i find problem is source to ANDROID_HOME not work. even if you execute after shell in Terminal

```
  export ANDROID_HOME=/your path/sdk
  export PATH=$ANDROID_HOME/platform-tools:$PATH
  export PATH=$ANDROID_HOME/tools:$PATH

 //make change with immediate effect 
  source ~/.bash_profile 
```

and execute 

```
   mao$ adb version  
   Android Debug Bridge version 1.0.32
   Revision eac51f2bb6a8-android
```

 the result is right ,but after next open window  ,the adb will not work,finally I check .bash_profile file  and I find in this file the var of ANDROID_HOME is not exist ,so I update .bash_profile manually and  the problem is solved .

**Comment by santoshgistto** [comment] 2015-10-19 18:10
@pedrovgs yes

**Comment by santoshgistto** [comment] 2015-10-19 18:20
@pedrovgs  cool its working now Thanks you :)
i restarted the studio.

**Comment by pedrovgs** [comment] 2015-10-19 22:29
@santoshgistto @tomer1 @lulumeya @itxuye can you check if this version I've uploaded to my drive is working for your? https://drive.google.com/file/d/0B9xkpTnF9BXjSk9VeU92MUt5M1E/view?usp=sharing Remember to uninstall your current plugin version and restart your IDE before to install this one.

**Comment by itxuye** [comment] 2015-10-20 01:54
@pedrovgs Yes,it's working now.Thaks you.~~~

**Comment by weiyideai520** [comment] 2015-10-20 02:05
it's working now,Thaks you.~~~

**Comment by santoshgistto** [comment] 2015-10-20 06:25
@pedrovgs  yes, its working.

Thank you

**Comment by matteosist** [comment] 2015-10-20 14:29
@pedrovgs i have the same error.

OS -> OSX El Captain

echo $ANDROID_HOME
/Users/msist/Library/Android/sdk/

sh-3.2# adb version
Android Debug Bridge version 1.0.32
Revision eac51f2bb6a8-android

sh-3.2# adb devices -l
List of devices attached
0693948a0b355c14       device usb:4195549184X product:hammerhead model:Nexus_5 device:hammerhead

how can fix it?

**Comment by lulumeya** [comment] 2015-10-20 14:31
@matteosist
In my case, I started studio in my terminal, and the plugin worked correctly.
May be GUI application launching context is different with our terminal

**Comment by pedrovgs** [comment] 2015-10-20 14:32
@matteosist I'm going to release a new version with the fix tonight. Review your bash profile configuration, your ANDROID_HOME should be exported there. I have a PR from @JcMinarro to avoid the ANDROID_HOME env var usage. Once be reviewed and merge I'll generate a new version with the fix. For you, the version 1.0.1 I'm going to release tonight will be enough. Regards!

**Comment by pedrovgs** [comment] 2015-10-20 17:38
Fixed in the Release 1.1 I've just published :)

**Closed as completed by pedrovgs** 2015-10-20 17:38 UTC
Labels: bug

**Comment by matteosist** [comment] 2015-10-21 07:36
Thanks. Link for download? :)

**Comment by pedrovgs** [comment] 2015-10-21 08:35
I've sent the new version but the IntelliJ store has to approve it. The plugin will be ready to download today or tomorrow. Here is the link -> https://plugins.jetbrains.com/plugin/7983

**Comment by santoshgistto** [comment] 2015-10-21 09:30
cool its very good tool :+1:  thank you :)

**Comment by pedrovgs** [comment] 2015-10-21 10:36
You are welcome @santoshgistto !

**Comment by Android-s14** [comment] 2015-10-22 14:13
@pedrovgs version 1.1 still doesn't work for me on linux. ANDROID_HOME is set in .bash_profile to point to the sdk, all correctly recognized from the IDEA's terminal, but not by the plugin.

**Comment by pedrovgs** [comment] 2015-10-22 14:19
Don't worry @Android-s14 I have a PR pending to be merged and a new release to avoid the usage of ANDROID_HOME ;)
